### ISSUE TITLE
Missing artifact com.alipay.sofa:rpc-sofa-boot-starter:jar:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by junweiHe** [alipay/sofa-boot#251]
I have been using SOFA-BOOT-3.0.0-SNAPSHOT before, it is normal, today pom can not find "rpc-sofa-boot-starter" 

eg. Missing artifact com.alipay.sofa:rpc-sofa-boot-starter:jar:3.0.0-SNAPSHOT

Is the jar in your maven repository missing?

**Comment by khotyn** [comment]
@QilongZhang Pls have a look at this, I think you change the wrong version of rpc-sofa-boot-starter in sofa-build:

<img width="1134" alt="2018-10-30 at 3 16 pm" src="https://user-images.githubusercontent.com/584455/47702069-c712db00-dc56-11e8-8fd3-a294ad11b1a4.png">

By the way, rpc-sofa-boot-starter's version is 5.x.x, change the version back to 3.x.x is too weird.

**Comment by QilongZhang** [comment]
@junweiHe  @khotyn   rpc-sofa-boot-starter managed by SOFABoot 3.0.0 is not compatible with previous version.  According to common sense, we should upgrade rpc-sofa-boot-starter major version to 6.x compared to previous 5.x version. 

However, the first version of rpc-sofa-boot-starter is 5.3.0, which is related to SOFARPC. After internal discussion, we change the version strategy that the major version of rpc-sofa-boot-starter   would follow SOFABoot instead of SOFARPC

**Comment by QilongZhang** [comment]
@khotyn @junweiHe  fixed in https://github.com/alipay/sofa-build/pull/6  and the rpc-sofa-boot-starterr:jar:6.0.0-SNAPSHOT have been uploaded.
